# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
 secret_key_base: ec8381d6af62bec07646332f373a977f373008b3959990e9e393c6c9b1d529a1b8691dcee8bc4e35dc8b4d2bc517edd7ac429ce6a537bdad47ab9770bc05590d
 database:
     :user: amazingcoders
     :password: amazing123

 stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
 stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>

test:
 secret_key_base: ee95e7c81e5a3892777368411ee7f6a5536010cc8c3a793a487cc8b328fc079c0ff20d70ddb1ebb3cd5bd0cc8374cd2245663e716ad056719ad1b57a7ba4063b
 database:
     :user: amazingcoders
     :password: amazing123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

 stripe_secret_key: <%= ENV["SECRET_KEY"] %>
 stripe_publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>